Modified script to make it more efficient and added few conditions.
AlabamaWaterInstitute/data_access_examples pull request #62
Opened 2023-06-07 20:53 UTC by RohanSunkarapalli

- Added a condition that if objecttype is set to forcing it automatically generates LDASIN files and doesn't incorporate other file types.
- Added the year condition for forcing from 1979 to 2006 that it should include minutes in the file name and for the rest of the time period it doesn't generate file names with minutes.

2023-06-13 23:39 UTC, jameshalgren commented on nwm_filenames/listofnwmfilenamesretro.py
>      return [file for file in valid_file_list if file is not None]
Can we move this to a helper function?

2023-06-13 23:40 UTC, jameshalgren commented on nwm_filenames/listofnwmfilenamesretro.py
>      return [file for file in valid_file_list if file is not None]
Done.

2023-06-13 23:45 UTC, jameshalgren requested changes
I combined the url check into a helper function. Can you make sure that it is properly checking the file existence per the comment?

2023-06-13 23:45 UTC, jameshalgren commented on nwm_filenames/listofnwmfilenames.py
> +    end_date = "20030420"
These produce invalid files, but generate a valid signature with the test... 
e.g., 
https://storage.cloud.google.com/national-water-model/nwm.20030420/medium_range_mem5/nwm.t12z.medium_range.reservoir_5.f158.conus.nc

is not a valid file.

2023-06-13 23:56 UTC, RohanSunkarapalli commented
> I combined the url check into a helper function. Can you make sure that it is properly checking the file existence per the comment?

Yes, I've verified with the updated changes and it works.

2023-06-14 00:00 UTC, RohanSunkarapalli commented
> I combined the url check into a helper function. Can you make sure that it is properly checking the file existence per the comment?

Yes, I've verified with the updated changes and it works.

2023-06-14 00:00 UTC, jameshalgren commented
> > I combined the url check into a helper function. Can you make sure that it is properly checking the file existence per the comment?
> 
> Yes, I've verified with the updated changes and it works.

Seems like the built-in test, for instance, is still producing files from the Google archive for which do not exist, but the validator is saying they do. 

`python listofnwmfilenames.py` returns a list including `'https://storage.cloud.google.com/national-water-model/nwm.20030420/medium_range_mem5/nwm.t12z.medium_range.reservoir_5.f158.conus.nc'`

which is not valide.

2023-06-16 21:32 UTC, jameshalgren approved these changes
Check URL was getting a 200 response from the "Authenticated URL", which is accurate because that is a sign-in page it is returning. 

We adjusted the test to use the public URL, and now invalid addresses properly return a 404.

2023-06-16 21:36 UTC, merged